[project]
name = "titanic"
version = "0.1.0"
description = "A package for Titanic data analysis"
authors = [
  { name = "Your Name", email = "your.email@example.com" }
]
readme = "README.md"
requires-python = ">=3.8"

